# Generated by Django 5.0.6 on 2024-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
    ]
